name: post_tweets

on:
  workflow_dispatch:
  schedule:
  - cron:  "0 8,17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
#         AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
#         DYNAMODB_PIPELINE_TABLE_NAME: ${{secrets.DYNAMODB_PIPELINE_TABLE_NAME }}
        api_key:  ${{secrets.api_key}}
        api_secret_key:  ${{secrets.api_secret_key}}
        access_token:  ${{secrets.access_token}}
        access_token_secret:  ${{secrets.access_token_secret}}
        bearer_token:  ${{secrets.bearer_token}}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      
      
      - name: Execute Python script # Run the app.py
        run: python random_tweet.py
